discord_server_id:
  type: string
  default: ""
discord_invite_url:
  type: string
  default: ""
require_login:
  type: bool
  default: false
minimum_trust_level:
  type: integer
  default: 0
require_staff:
  type: bool
  default: false
required_groups:
  type: list
  list_type: group
  default: ""
theme:
  type: enum
  choices:
    - light
    - dark
    - auto
  default: auto
